name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Test input: ${{ github.event.inputs.test_input }}"
          echo "This is a test manual workflow"